name: Go Build

on:
  push:
    branches: [ci]
  pull_request:
    branches: [ci]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod tidy

      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o mempass-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mempass-${{ matrix.os }}-${{ matrix.arch }}
          path: mempass-${{ matrix.os }}-${{ matrix.arch }}
